# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a Node.js image for building
FROM node:16-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package files and install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the TypeScript files
RUN npm run build

# Start a new stage from the base image for the release
FROM node:16-alpine AS release

# Set the working directory
WORKDIR /app

# Copy built files and necessary packages from the builder stage
COPY --from=builder /app/build /app/build
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev

# Set environment variables for the application
ENV NODE_ENV=production

# Define the command to run the application
ENTRYPOINT ["node", "build/index.js"]
